---

- name: "add Zabbix official repository"
  yum_repository:
    name: zabbix
    baseurl: http://repo.zabbix.com/zabbix/{{ zabbix_agent_release }}/rhel/{{ ansible_distribution_major_version }}/$basearch/
    gpgcheck: 0
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    state: present
